#!/usr/bin/env python3

import os


buildfile = "build_version.py"

with open(buildfile, 'r') as f:
    lines = f.readlines()

version = None

for idx, line in enumerate(lines):
    if not line.lstrip().startswith('#') and 'Override' in line:
        print(f"Found line with version override, aborting")
        print(line)
        exit(1)

    if not line.startswith('#') and 'BuildVersion' in line:
        parts = line.split("'")
        version = parts[1]



if version == None:
    print(f"Could not find version number, version={version}")
    exit(1)


os.system('git add build_version.py')
os.system(f'git commit -m "bump build version to {version}"')
print(f'git commit -m "bump build version to {version}"')
