#!/bin/bash

# Deploy my minimal nvim config to a host after removing unneeded files
cp -r ~/.config/nvim ~/random/tmp/
cd ~/random/tmp/nvim
git checkout minimal
rm -rf .git .gitignore

cd ..
scp -r nvim ${1}:~/.config
rm -rf nvim
