#!/usr/bin/env python3
import sys

buildfile = "build_version.py"

with open(buildfile, 'r') as f:
    lines = f.readlines()

increment_count = int(sys.argv[1]) if len(sys.argv) > 1 else 1
to_increment_idx = None
incremented_line = None
version_num = None

for idx, line in enumerate(lines):
    if not line.startswith('#') and 'BuildVersion' in line:
        parts = line.split('.')
        smaller_version = parts[2]
        if not smaller_version.startswith('0'):
            print("Smaller version number is not 0, abort")
            exit(1)

        version_num = int(parts[1])
        parts[1] = str(version_num + increment_count)

        incremented_line = '.'.join(parts)
        to_increment_idx = idx
        break

if to_increment_idx == None or incremented_line == None or version_num == None:
    print(f"Could not find line to increment, increment_idx={to_increment_idx}, new line={incremented_line}, version_num={version_num}")
    exit(1)

lines[to_increment_idx] = incremented_line
with open(buildfile, 'w') as f:
    f.writelines(lines)

print(f"Bumped build version from {version_num} to {version_num + increment_count}")
