#!/usr/bin/python3.10
import argparse

from services.key_manager import KeyManager, load_keys


parser = argparse.ArgumentParser()
parser.add_argument('-a', '--account')
parser.add_argument('-e', '--exchange')
parser.add_argument('--type')
parser.add_argument('-t', '--tags', action="append", default=[])
args = parser.parse_args()

args.tags = set(args.tags)

key_file = "/home/shreyash/master-config/subprojects/exchange_configs/keys.toml"
keyman = KeyManager(load_keys(key_file))

kwargs = {k:v for k, v in vars(args).items() if v is not None}

name = keyman.get(**kwargs)
key_dict = keyman.key_info[name]
print(f"{name}")
for k, v in key_dict.items():
    print(f'{k} = "{v}",')

