#!/bin/bash

CURRENT_BUILD="crypto_prod-1.404.0"
CURRENT_RELEASE="crypto_prod-1.559.0"

echo "Current build         ${CURRENT_BUILD}"
echo "Current release       ${CURRENT_RELEASE}"
echo
echo "Sourcing runtime libs"

export PYTHONPATH=/home/melzi-prod/melzi/crypto_prod/builds/${CURRENT_BUILD}/lib64/:/home/melzi-prod/melzi/crypto_prod/build/${CURRENT_BUILD}/tools/
export LD_LIBRARY_PATH=/home/melzi-prod/melzi/crypto_prod/builds/${CURRENT_BUILD}/lib64/:/home/melzi-prod/melzi/toolchains/gcc-10.3.0/lib64/:.
export PRODUCT_CONFIG_FILE=/home/melzi-prod/melzi/crypto_prod/releases/${CURRENT_RELEASE}/product_definitions/product_config_all.toml
export FEATURE_MAP_FILE=/home/melzi-prod/melzi/crypto_prod/releases/${CURRENT_RELEASE}/product_definitions/product_feature_map.toml

# export PYTHONPATH=/home/melzi-prod/melzi/crypto_prod/builds/${CURRENT_BUILD}/lib64/:$PYTHON_PATH
# export LD_LIBRARY_PATH=/home/melzi-prod/melzi/crypto_prod/builds/${CURRENT_BUILD}/lib64/:/home/melzi-prod/melzi/toolchains/gcc-10.3.0/lib64/:.
