#!/usr/bin/python3.10
from crypto_clients.utils import filter_by_account, filter_by_exchange, filter_by_kind, filter_by_pattern, get_all_product_definitions
from pprint import pprint
import argparse

parser = argparse.ArgumentParser()
parser.add_argument('-a', '--account')
parser.add_argument('--kind', choices=["spot", "future", "perpetual"])
parser.add_argument('--api')
parser.add_argument('--pattern')
parser.add_argument('--exchange')
args = parser.parse_args()


product_config_all = "/home/shreyash/prod-config/subprojects/product_config/product_config_all.toml"
products = get_all_product_definitions(product_config_all)

if args.account:
    products = filter_by_account(products, args.account)

if args.kind:
    products = filter_by_kind(products, args.kind)

if args.api:
    products = [p for p in products if p.api == args.api]

if args.pattern:
    products = filter_by_pattern(products, args.pattern.upper())

if args.exchange:
    products = filter_by_exchange(products, args.exchange.upper())


product_names = [p.product for p in products]
pprint(product_names)
print(len(product_names))
