#!/usr/bin/python3
import os
import json
import argparse

# TODO: fix this
def get_box_address(product: str):
    segments = [('main','crypto_prod'), ('beta', 'crypto')]
    for segment, organization in segments:
        manifest_path = os.popen(f'ls -td /mnt/releases/{organization}/releases/{organization}-* | head -1').read()[:-1] + "/manifest.json"
        data = json.loads(open(manifest_path,'rb').read())
        process = None
        services = data['segments'][segment]['segment_config']['services']
        for key in services.keys():
            if product in services[key]['products']:
                process = key
                break
        if not process:
            continue
        node = process.split('.')[0]
        node_address = data['segments'][segment]['segment_config']['nodes'][node]['address']
        return node_address, segment
    return None, None


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('product')
    args = parser.parse_args()

    print(args.product)
    print(get_box_address(args.product))
