#!/bin/bash

cd ~/crypto/subprojects/position_reconciliation
git checkout rest_api
cp -r ~/crypto/subprojects/position_reconciliation ~/random/tmp/
git checkout -
cd ~/random/tmp/position_reconciliation

rsync restart_reconcile.sh melzi-prod@lws1:~/scripts/rest_pos_recon/
rsync -r reconcile/*py melzi-prod@lws1:~/scripts/rest_pos_recon/reconcile/
rm -rf position_reconciliation
